"""Strict checks, warning-only drafts, located reports and protected writes."""
import argparse
import json
import subprocess
import tempfile
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    for name in ('sema', 'coge'):
        parser.add_argument('--' + name, required=True, type=Path)
    args = parser.parse_args()
    cases = 0

    def run(binary, *arguments, ok=True, code=None):
        nonlocal cases
        result = subprocess.run([str(binary), *map(str, arguments)], capture_output=True, text=True)
        assert (result.returncode == 0) == ok, result.stdout + result.stderr
        if code:
            assert code in result.stderr, result.stderr
        cases += 1
        return result

    with tempfile.TemporaryDirectory(prefix='agsem-completeness-') as temp:
        root = Path(temp)
        draft = root / 'draft.sema'
        draft.write_text('// Zażółć\nsema Draft; grammar Draft; node start : ID; ID:\'a\';')
        report = root / 'report.json'
        result = run(args.sema, '--check', '--report', report, draft, code='completeness.pending')
        assert 'warning:' in result.stderr
        model = json.loads(report.read_text())
        assert model['format'] == 'agsem-completeness-v1'
        assert model['targets'] == ['analysis'] and not model['results'][0]['complete']
        actions = [o for o in model['obligations'] if o['key']['kind'] == 'analysis_action']
        assert len(actions) == 1 and actions[0]['state'] == 'pending'
        assert actions[0]['location']['file'] == str(draft) and actions[0]['location']['line'] == 2
        assert actions[0]['diagnostics'] and model['diagnostics'][actions[0]['diagnostics'][0]]['code'] == 'completeness.pending'
        first = report.read_bytes()
        result = run(args.sema, '--check-complete', '--report', report, '--force', draft, ok=False, code='completeness.pending')
        assert 'error:' in result.stderr and report.read_bytes() == first
        run(args.sema, '--check', '--report', report, draft, ok=False, code='output exists')
        run(args.sema, '--check', '--report', draft, '--force', draft, ok=False, code='output.would_overwrite_input')
        alias = root / 'alias.json'
        alias.symlink_to(draft)
        run(args.sema, '--check', '--report', alias, '--force', draft, ok=False, code='output.would_overwrite_input')
        run(args.sema, '--emit-ag', root / 'draft.ag', draft)
        run(args.sema, '--emit-rust-dir', root / 'rust', draft, ok=False, code='completeness.pending')
        assert not (root / 'rust').exists()
        rust = root / 'existing-rust'
        rust.mkdir()
        for name in ('sema_gen.rs', 'sema_modules.manifest', 'sema_generation.provenance.json'):
            (rust / name).write_text('preserve ' + name)
        (rust / 'sema_modules.manifest').write_text('agsem-modules-v1\nsema_old_gen.rs\n')
        (rust / 'sema_generation.provenance.json').write_text(
            json.dumps({'format': 'agsem-generation-provenance-v1'}))
        (rust / 'sema_old_gen.rs').write_text('// Generated by sema\npreserve owned module')
        before = {p.name: p.read_bytes() for p in rust.iterdir()}
        run(args.sema, '--emit-rust-dir', rust, '--force', draft,
            ok=False, code='completeness.pending')
        assert {p.name: p.read_bytes() for p in rust.iterdir()} == before

        grammar = root / 'unit.ag'
        grammar.write_text("grammar UnitDoc; node start : ID #Start; ID:'a';")
        unit = root / 'unit.sema'
        run(args.sema, '--from-ag', grammar, '--emit-template', unit)
        contract = root / 'context.json'
        contract.write_text(json.dumps({'format': 1, 'id': 'admission', 'version': '1',
                                       'semantic': [{'name': 'Context', 'kind': 'opaque'}]}))
        text = unit.read_text().replace('grammar UnitDoc;',
            'grammar UnitDoc; semantic_model { rust_context Context; analyzer start() -> Int; }')
        # A valid body must not turn an explicitly pending action into a proof.
        text = text.replace('analysis {\n    }', 'analysis { result = 1; }')
        unit.write_text(text)
        run(args.sema, '--emit-rust-dir', root / 'unit-rust', '--contracts', contract, unit,
            ok=False, code='completeness.pending')
        unit.write_text(text.replace('state pending;', 'state implemented;'))
        run(args.sema, '--emit-rust-dir', root / 'unit-rust', '--contracts', contract, unit)
        assert (root / 'unit-rust' / 'sema_gen.rs').exists()
        invalid_body = root / 'pending-invalid.sema'
        invalid_body.write_text(text.replace('result = 1;', 'result = true;'))
        invalid_body_report = root / 'pending-invalid.json'
        run(args.sema, '--check', '--report', invalid_body_report, '--contracts', contract,
            invalid_body, ok=False, code='action.invalid_alternative')
        mixed = json.loads(invalid_body_report.read_text())
        assert any(d['code'] == 'action.invalid_alternative' and d['severity'] == 'error'
                   for d in mixed['diagnostics'])
        assert any(d['code'] == 'completeness.pending' and d['severity'] == 'warning'
                   for d in mixed['diagnostics'])
        assert any(o['key']['kind'] == 'analysis_action' and o['state'] == 'pending'
                   and o['validation'] == 'invalid' for o in mixed['obligations'])
        # Logical completeness does not add support for an emitter's AST shape.
        empty_grammar = root / 'empty.ag'
        empty_grammar.write_text("grammar EmptyDoc; node start : empty #Start; ID:'a';")
        empty_document = root / 'empty.sema'
        run(args.sema, '--from-ag', empty_grammar, '--emit-template', empty_document)
        empty_document.write_text(empty_document.read_text().replace('grammar EmptyDoc;',
            'grammar EmptyDoc; semantic_model { rust_context Context; analyzer start() -> Unit; }')
            .replace('state pending;', 'state no_action; reason "empty language";'))
        empty_report = root / 'empty.json'
        run(args.sema, '--check-complete', '--report', empty_report, '--contracts', contract,
            empty_document)
        empty_model = json.loads(empty_report.read_text())
        assert empty_model['results'][0]['complete'] and not empty_model['results'][0]['can_emit']
        assert not any(d['severity'] == 'error' for d in empty_model['diagnostics'])
        run(args.sema, '--emit-rust-dir', rust, '--force', '--contracts', contract,
            empty_document, ok=False, code='document.unsupported_construct')
        assert {p.name: p.read_bytes() for p in rust.iterdir()} == before
        for target in ('c', 'interpreter'):
            coge_target = root / (target + '.coge')
            coge_target.write_text(unit.read_text().replace('sema UnitDoc;', 'coge UnitDoc;') +
                                   ' execution_obligations { targets "' + target + '"; }')
            run(args.coge, '--emit-rust-dir', rust, '--force', '--contracts', contract,
                coge_target, ok=False, code='completeness.pending')
            assert {p.name: p.read_bytes() for p in rust.iterdir()} == before
        coge = root / 'draft.coge'
        coge.write_text(draft.read_text().replace('sema Draft;', 'coge Draft;'))
        run(args.coge, '--emit-rust-dir', rust, '--force', coge,
            ok=False, code='completeness.pending')
        assert {p.name: p.read_bytes() for p in rust.iterdir()} == before
        run(args.coge, '--check-complete', '--target', 'c', '--report', report, '--force', coge, ok=False)
        model = json.loads(report.read_text())
        assert model['targets'] == ['analysis', 'lowering', 'c']
        assert any(o['key']['kind'] == 'backend_binding' and o['state'] == 'pending' for o in model['obligations'])
        assert not any(o['key']['kind'] == 'execute_handler' for o in model['obligations'])
        run(args.sema, '--check', '--target', 'c', draft, ok=False, code='--target requires coge')
        run(args.coge, '--check', '--target', 'c', '--target', 'c', coge, ok=False, code='duplicate')
        run(args.sema, '--check', '--report', report, draft, draft, ok=False, code='exactly one input')
        invalid = root / 'invalid.sema'
        invalid.write_text('sema broken ???')
        invalid_report = root / 'invalid.json'
        run(args.sema, '--check-complete', '--report', invalid_report, invalid, ok=False)
        assert not invalid_report.exists()
    print(f'Completeness CLI: {cases} cases passed')


if __name__ == '__main__':
    main()
