#include "coge/InterpreterGeneration.h"

#include <sstream>
#include <stdexcept>

namespace coge {

auto emitInterpreterRust(const std::optional<InterpreterGenerationPlan> &plan)
    -> std::string {
  if (!plan)
    return {};
  std::ostringstream output;
  output << (plan->declarations
                 ? "// Generated by sema from execution_model and "
                   "execution_contract.\n"
                 : "// Generated by sema from execution_contract.\n");
  std::ostringstream methods;
  if (plan->declarations) {
    output << emitExecutionDeclarationsRust(*plan->declarations,
                                            plan->contextType);
    if (plan->declarations->functions.size() != plan->functionBodies.size())
      throw std::runtime_error("execution function plan mismatch");
    for (std::size_t index = 0; index < plan->functionBodies.size(); ++index) {
      methods << emitExecutionFunctionSignatureRust(
          plan->declarations->functions[index]);
      methods << emitExecutionBodyRust(plan->functionBodies[index]);
      methods << "    }\n\n";
    }
  }
  output << "impl<'a> Interpreter<'a> {\n"
         << methods.str()
         << "    fn execute_generated(&mut self, kind: Operation, source: "
            "InputSpan) -> Result<Control, RuntimeError> {\n"
            "        match kind {\n";
  for (const auto &arm : plan->operations)
    output << "            "
           << (arm.structuredPattern
                   ? emitExecutionPatternRust(*arm.structuredPattern)
                   : arm.pattern)
           << " => {\n"
           << emitExecutionBodyRust(arm.body) << "            }\n";
  output << "        }\n    }\n\n"
            "    fn evaluate_generated(&mut self, kind: ExpressionKind, "
            "checks: Vec<RuntimeCheck>, expression: ExprId, source: InputSpan) "
            "-> Result<Value, RuntimeError> {\n"
            "        match kind {\n";
  for (const auto &arm : plan->expressions)
    output << "            "
           << (arm.structuredPattern
                   ? emitExecutionPatternRust(*arm.structuredPattern)
                   : arm.pattern)
           << " => {\n"
           << emitExecutionBodyRust(arm.body) << "            }\n";
  output << "        }\n    }\n}\n";
  return output.str();
}

} // namespace coge
