#include "coge/BackendGeneration.h"

#include "agas/artifact/Sha256.h"
#include <nlohmann/json.hpp>
#include <stdexcept>
#include <tuple>

namespace coge {

auto prepareBackends(const BackendGenerationInput &input) -> CheckedBackends {
  CheckedBackends checked;
  const auto expand = [&](BackendBinding binding, const std::string &profile,
                          const std::string &emit) {
    const bool explicitEmit = !binding.emit.empty();
    const bool explicitLower = !binding.lower.empty();
    if (!binding.profile.empty()) {
      if (binding.profile != profile)
        throw std::runtime_error("unknown backend profile: " + binding.profile);
      if (binding.emit.empty())
        binding.emit = emit;
      if (binding.lower.empty() && input.lowering)
        binding.lower = *input.lowering;
    }
    if (binding.emit.empty() || binding.lower.empty())
      throw std::runtime_error("backend requires emit and lower bindings");
    using Json = nlohmann::ordered_json;
    const bool llvm = profile == "core_llvm_v1";
    Json schema{{"id", profile},
                {"default_emit", emit},
                {"lower_source", "checked_lowering"},
                {"effect", "pure"},
                {"context_parameter", "&Context"},
                {"function_parameter", "FunctionId"},
                {"target_parameter",
                 llvm ? Json("agsem_runtime::llvm_backend::TargetSpec")
                      : Json(nullptr)},
                {"input", "agsem_runtime::structured_ir::Module"},
                {"result", "Result<String, backend error>"},
                {"runtime", llvm ? "agsem_runtime::llvm_backend::emit_llvm"
                                 : "agsem_runtime::c_backend::emit_c"}};
    Json report{
        {"profile",
         binding.profile.empty()
             ? Json(nullptr)
             : Json{{"id", binding.profile},
                    {"sha256", agas::artifact::sha256Hex(schema.dump())}}},
        {"interface", schema},
        {"bindings", Json::array()}};
    for (const auto &[role, value, explicitValue] :
         {std::tuple{"emit", binding.emit, explicitEmit},
          std::tuple{"lower", binding.lower, explicitLower}}) {
      Json entry{{"role", role},
                 {"target", value},
                 {"origin", explicitValue ? "explicit"
                                          : (std::string{role} == "lower"
                                                 ? "checked_lowering"
                                                 : "profile_default")}};
      const auto location =
          binding.locations.find(explicitValue ? role : "profile");
      if (location != binding.locations.end()) {
        entry["begin_byte"] = location->second.beginByte;
        entry["end_byte"] = location->second.endByte;
      }
      report["bindings"].push_back(std::move(entry));
    }
    binding.inspection = report.dump();
    return binding;
  };
  if (input.c) {
    if (!input.lowering)
      throw std::runtime_error("backend_c requires lowering_model");
    auto binding = expand(*input.c, "core_c_v1", "emit_c");
    if (binding.lower != *input.lowering)
      throw std::runtime_error("backend_c lower differs from lowering_model");
    checked.c_ = std::move(binding);
  }
  if (input.llvm) {
    if (!input.lowering)
      throw std::runtime_error("backend_llvm requires lowering_model");
    auto binding = expand(*input.llvm, "core_llvm_v1", "emit_llvm");
    if (binding.lower != *input.lowering)
      throw std::runtime_error(
          "backend_llvm lower differs from lowering_model");
    checked.llvm_ = std::move(binding);
  }
  return checked;
}

auto emitCBackendRust(const CheckedBackends &backends) -> std::string {
  if (!backends.c())
    return {};
  const auto &emit = backends.c()->emit;
  const auto &lower = backends.c()->lower;
  return "// Generated by sema from backend_c.\n"
         "use crate::model::{Context, FunctionId};\n\n"
         "#[derive(Debug)]\n"
         "pub enum BackendCError {\n"
         "    Lowering(&'static str),\n"
         "    Emission(agsem_runtime::c_backend::EmitError),\n"
         "}\n\n"
         "pub fn " +
         std::string{emit} +
         "(ctx: &Context, function: FunctionId) -> Result<String, "
         "BackendCError> {\n"
         "    let ir = crate::lowering_gen::" +
         std::string{lower} +
         "(ctx, function).map_err(BackendCError::Lowering)?;\n"
         "    "
         "agsem_runtime::c_backend::emit_c(&ir).map_err(BackendCError::"
         "Emission)\n"
         "}\n";
}

auto emitLlvmBackendRust(const CheckedBackends &backends) -> std::string {
  if (!backends.llvm())
    return {};
  const auto &emit = backends.llvm()->emit;
  const auto &lower = backends.llvm()->lower;
  return "// Generated by sema from backend_llvm.\n"
         "use crate::model::{Context, FunctionId};\n"
         "use agsem_runtime::llvm_backend::TargetSpec;\n\n"
         "#[derive(Debug)]\n"
         "pub enum BackendLlvmError {\n"
         "    Lowering(&'static str),\n"
         "    Emission(agsem_runtime::llvm_backend::EmitError),\n"
         "}\n\n"
         "pub fn " +
         std::string{emit} +
         "(ctx: &Context, function: FunctionId, target: TargetSpec<'_>) -> "
         "Result<String, BackendLlvmError> {\n"
         "    let ir = crate::lowering_gen::" +
         std::string{lower} +
         "(ctx, function).map_err(BackendLlvmError::Lowering)?;\n"
         "    agsem_runtime::llvm_backend::emit_llvm(&ir, "
         "target).map_err(BackendLlvmError::Emission)\n"
         "}\n";
}

} // namespace coge
